name: infra
on:
  workflow_dispatch:
  push:
    paths: ["infra/**"]

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Terraform init & apply
        working-directory: infra/main
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="region=${{ secrets.AWS_REGION }}" \
            -var="name_prefix=wiz" \
            -var="backup_bucket=${{ secrets.MONGO_BACKUP_BUCKET }}" \
            -var="ec2_ssh_public_key=${{ secrets.EC2_SSH_PUBLIC_KEY }}"

      - name: Enable EKS control plane logs
        run: |
          CLUSTER=$(terraform -chdir=infra/main output -raw cluster_name)
          aws eks update-cluster-config --name "$CLUSTER" \
            --logging 'clusterLogging={enableTypes=["api","audit","authenticator","controllerManager","scheduler"]}'

      - name: Install AWS Load Balancer Controller (Helm)
        run: |
          CLUSTER=$(terraform -chdir=infra/main output -raw cluster_name)
          aws eks update-kubeconfig --name "$CLUSTER" --region "${{ secrets.AWS_REGION }}"
          VPC_ID=$(terraform -chdir=infra/main output -raw vpc_id)
          helm repo add eks https://aws.github.io/eks-charts
          helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
            -n kube-system --create-namespace \
            --set clusterName="$CLUSTER" \
            --set region="${{ secrets.AWS_REGION }}" \
            --set vpcId="$VPC_ID" \
            --set serviceAccount.create=true

      - name: Show important outputs
        run: |
          terraform -chdir=infra/main output
